---
roles:
  - src: ten7.flightdeck_base
    version: 5.1.3
  - src: ten7.digitalocean_kubeconfig
  - src: ten7.digitalocean_domain
    version: 1.1.0
  - src: ten7.flightdeck_cluster
    version: 1.5.3
  - src: ten7.pantheon_deploy
    version: 1.3.3
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.mysql
  - name: community.kubernetes
